### ISSUE TITLE
Support for unsafe blocks

### ISSUE THREAD

**Issue by RobbeDGreef** [mtshiba/ruast#6]
I couldn't find a way to create unsafe expressions/blocks in ruast. This is something I need for my use case, so if I did not miss anything, and there is no way of doing that currently in ruast, I wanted to ask what the best way of implementing this would be.

In the syn crate, this is handled by the [ExprUnsafe struct](https://docs.rs/syn/2.0.85/syn/struct.ExprUnsafe.html), while in rustc_ast, the [block struct](https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/struct.Block.html) has a `rules` field, which specifies the safety of the block.

Personally my preference goes out to creating a safety field in the Block struct, but any other way is fine as well. 
Let me know what you think, thanks!

**Comment by mtshiba** [comment]
I forgot to support unsafe expressions (and const blocks). I'll add them in the next version.

**Comment by mtshiba** [comment]
Added [`Expr::UnsafeBlock`](https://docs.rs/ruast/0.0.8/ruast/struct.UnsafeBlock.html). In addition to `UnsafeBlock::new`, it can also be created using the `Block::unsafe_()` or `Expr::into_unsafe()` methods.

**Comment by RobbeDGreef** [comment]
Awesome, thanks!
